{% set version = "1.1.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-s2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/s2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/s2/s2_{{ version }}.tar.gz
  sha256: 4dcd2bff738be5a89b925fed29acb6e224e0f514b4530dc9987a0a72c5a99b55

build:
  # >>> begin debug
  skip: true  # [not win]
  # <<< end debug
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-wk                         # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}which             # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-wk >=0.6.0
    - libabseil                    # [not win]
    - openssl
  run:
    - r-base
    - r-rcpp
    - r-wk >=0.6.0

test:
  commands:
    - $R -e "library('s2')"           # [not win]
    - "\"%R%\" -e \"library('s2')\""  # [win]

about:
  home: https://r-spatial.github.io/s2/
  dev_url: https://github.com/r-spatial/s2
  doc_url: https://s2geometry.io/
  license: Apache-2.0
  summary: Provides R bindings for Google's s2 library for geometric calculations on the sphere. High-performance constructors and exporters provide high compatibility with existing spatial packages, transformers construct new geometries from existing geometries, predicates provide a means to select geometries based on spatial
    relationships, and accessors extract information about geometries.
  license_family: APACHE
  license_file:
    - LICENSE
    - tools/vendor/abseil-cpp/LICENSE  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
